[package]
name = "client_preparator"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
walkdir = { workspace = true }
chrono = { workspace = true }
ron = { workspace = true }
serde = { workspace = true }