[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
uuid = { workspace = true }
strum = { version = "0.26", features = ["derive"] }
byteorder = { version = "1.5.0" }
